In [1]:
# importing packages

import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#data read

data=pd.read_csv('germany.csv')
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,0
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,0
3,0,135,68,42,250,42.3,0.365,24,0
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,1
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,1
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,1

In [3]:
#EDA fucntion from previous work
def expl_data_analisys(source_frame):

    display(source_frame)
    source_frame.info()
    print()


    print ('\033[1m' + 'Null data amount' + '\033[0m')
    print()
    print(source_frame.isna().mean().sort_values(ascending = False).round(4) * 100)
    print()
    print('\033[1m' + 'Null data for float, int, %' + '\033[0m')
    print()
    for col in source_frame:
        if source_frame[col].dtypes in (float, int):
            print('{: >0}'.format(col), source_frame.loc[source_frame[col]==0, col].count())
    print()
    

    print('\033[1m' + 'Categorial variables' + '\033[1m')
    print()
    for col in source_frame:
        if source_frame[col].dtypes == object:
            print(('{: ^50}'.format(col)))
            display(source_frame[col].value_counts())
            print()


    print('\033[1m' + 'Quantitative variables' + '\033[1m')
    display(source_frame.describe())

In [6]:
#pass data to eda function 
#similar to dataprint info() and describe()
pre_process_data = expl_data_analisys(data)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,0
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,0
3,0,135,68,42,250,42.3,0.365,24,0
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,1
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,1
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               2000 non-null   int64
 1   Glucose                   2000 non-null   int64
 2   BloodPressure             2000 non-null   int64
 3   SkinThickness             2000 non-null   int64
 4   Insulin                   2000 non-null   int64
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64
 8   Outcome                   2000 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 140.8 KB

Null data amount

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
Outcome                     0.0
dtype: float64

Null data for float, int, %

Pregnancies 301
Glucose 13
BloodPressure 90
SkinThickness 573
Insulin 956
BMI 28
DiabetesPedigreeFunction 0
Age 0
Outcome 1316

Categorial variables

Quantitative variables

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,3.703500,121.182500,69.145500,20.935000,80.254000,32.193000,0.470930,33.090500,0.342000
std,3.306063,32.068636,19.188315,16.103243,111.180534,8.149901,0.323553,11.786423,0.474498
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,63.500000,0.000000,0.000000,27.375000,0.244000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,40.000000,32.300000,0.376000,29.000000,0.000000
75%,6.000000,141.000000,80.000000,32.000000,130.000000,36.800000,0.624000,40.000000,1.000000
max,17.000000,199.000000,122.000000,110.000000,744.000000,80.600000,2.420000,81.000000,1.000000

In [8]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,0
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,0
3,0,135,68,42,250,42.3,0.365,24,0
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,1
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,1
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,1

In [9]:
#null value removing with true and false 

#findout empty value and replace it with anything else 

data[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI']] = data[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI']].replace(0,np.NaN)

In [10]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2.0,138.0,62.0,35.0,NaN,33.6,0.127,47,0
1,NaN,84.0,82.0,31.0,125.0,38.2,0.233,23,0
2,NaN,145.0,NaN,NaN,NaN,44.2,0.630,31,0
3,NaN,135.0,68.0,42.0,250.0,42.3,0.365,24,0
4,1.0,139.0,62.0,41.0,480.0,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2.0,75.0,64.0,24.0,55.0,29.7,0.370,33,1
1996,8.0,179.0,72.0,42.0,130.0,32.7,0.719,36,1
1997,6.0,85.0,78.0,NaN,NaN,31.2,0.382,42,1
1998,NaN,129.0,110.0,46.0,130.0,67.1,0.319,26,1
1999,2.0,81.0,72.0,15.0,76.0,30.1,0.547,25,1

In [11]:
#empty value count
data.isnull().sum()

Pregnancies                 301
Glucose                      13
BloodPressure                90
SkinThickness               573
Insulin                     956
BMI                          28
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [12]:
#replacing NaN value with mean value 
data['Pregnancies'].fillna(data['Pregnancies'].mean(),inplace=True)
data['Glucose'].fillna(data['Glucose'].mean(), inplace = True)
data['BloodPressure'].fillna(data['BloodPressure'].mean(), inplace = True)
data['SkinThickness'].fillna(data['SkinThickness'].median(), inplace = True)
data['Insulin'].fillna(data['Insulin'].median(), inplace = True)
data['BMI'].fillna(data['BMI'].median(), inplace = True)

In [13]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2.000000,138.0,62.000000,35.0,126.0,33.6,0.127,47,0
1,4.359623,84.0,82.000000,31.0,125.0,38.2,0.233,23,0
2,4.359623,145.0,72.403665,29.0,126.0,44.2,0.630,31,0
3,4.359623,135.0,68.000000,42.0,250.0,42.3,0.365,24,0
4,1.000000,139.0,62.000000,41.0,480.0,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2.000000,75.0,64.000000,24.0,55.0,29.7,0.370,33,1
1996,8.000000,179.0,72.000000,42.0,130.0,32.7,0.719,36,1
1997,6.000000,85.0,78.000000,29.0,126.0,31.2,0.382,42,1
1998,4.359623,129.0,110.000000,46.0,130.0,67.1,0.319,26,1
1999,2.000000,81.0,72.000000,15.0,76.0,30.1,0.547,25,1

In [14]:
#splitting data into dependend and independent

out = data['Outcome']
without_out = data.drop(['Outcome'],axis=1)

In [26]:
#importing all packages 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPRegressor

In [17]:
#train and test data 
without_out_train,without_out_test,out_train,out_test = train_test_split(without_out,out)

In [24]:
#implementing logistic regression 

logistic = LogisticRegression(random_state = 0)
logistic.fit(without_out_train,out_train)
logistic_pred = logistic.predict(without_out_test)
logistic_score = accuracy_score(out_test,logistic_pred)
precission_logistic = precision_score(out_test,logistic_pred)
recall_logistic = recall_score(out_test,logistic_pred)
f1_logistic = f1_score(out_test,logistic_pred)
print("Accuracy : ",logistic_score)
print("Precission : ",precission_logistic)
print("Recall : ",recall_logistic)
print("F1 : ",f1_logistic)

Accuracy :  0.67
Precission :  0.0
Recall :  0.0
F1 :  0.0

/home/moon/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/moon/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [29]:
#implementing random forest
random_forest = RandomForestClassifier(n_estimators = 100, random_state = 0)
random_forest.fit(without_out_train,out_train)
random_forest_pred = random_forest.predict(without_out_test)
random_forest_score = accuracy_score(out_test,random_forest_pred)
precission_random = precision_score(out_test,random_forest_pred)
recall_random = recall_score(out_test,random_forest_pred)
f1_random = f1_score(out_test,random_forest_pred)
print("Accuracy : ",random_forest_score)
print("Precission : ",precission_random)
print("Recall : ",recall_random)
print("F1 : ",f1_random)

Accuracy :  0.482
Precission :  0.11475409836065574
Recall :  0.08484848484848485
F1 :  0.09756097560975609

In [39]:
#implementing MLP 
#showing error for outcome value binary


#mlp = MLPRegressor(solver='lbfgs', hidden_layer_sizes=50, max_iter=1200,random_state=1)
#mlp.fit(without_out_train,out_train)
#mlp_pred = mlp.predict(without_out_test)
#mlp_score = accuracy_score(out_test,mlp_pred)
#precission_mlp = precision_score(out_test,mlp_pred)
#recall_mlp = recall_score(out_test,mlp_pred)
#f1_mlp = f1_score(out_test,mlp_pred)
#print("Accuracy : ",mlp_score)
#print("Precission : ",precission_mlp)
#print("Recall : ",recall_mlp)
#print("F1 : ",f1_mlp)

In [38]:
#implementing decisiontree

tree = DecisionTreeClassifier()
tree.fit(without_out_train,out_train)
tree_pred = tree.predict(without_out_test)
tree_score = accuracy_score(out_test,tree_pred)
precission_tree = precision_score(out_test,tree_pred)
recall_tree = recall_score(out_test,tree_pred)
f1_tree = f1_score(out_test,tree_pred)
print("Accuracy : ",tree_score)
print("Precission : ",precission_tree)
print("Recall : ",recall_tree)
print("F1 : ",f1_tree)

Accuracy :  0.546
Precission :  0.13095238095238096
Recall :  0.06666666666666667
F1 :  0.08835341365461846

In [41]:
#implementing KMeans

kn = KNeighborsClassifier()
kn.fit(without_out_train,out_train)
kn_pred = kn.predict(without_out_test)
kn_score = accuracy_score(out_test,kn_pred)
precission_kn = precision_score(out_test,kn_pred)
recall_kn = recall_score(out_test,kn_pred)
f1_kn = f1_score(out_test,kn_pred)
print("Accuracy : ",kn_score)
print("Precission : ",precission_kn)
print("Recall : ",recall_kn)
print("F1 : ",f1_kn)

Accuracy :  0.552
Precission :  0.16853932584269662
Recall :  0.09090909090909091
F1 :  0.11811023622047245

In [42]:
#implementing GaussianNB

gnb = GaussianNB()
gnb.fit(without_out_train,out_train)
gnb_pred = gnb.predict(without_out_test)
gnb_score = accuracy_score(out_test,gnb_pred)
precission_gnb = precision_score(out_test,gnb_pred)
recall_gnb = recall_score(out_test,gnb_pred)
f1_gnb = f1_score(out_test,gnb_pred)
print("Accuracy : ",gnb_score)
print("Precission : ",precission_gnb)
print("Recall : ",recall_gnb)
print("F1 : ",f1_gnb)

Accuracy :  0.648
Precission :  0.35135135135135137
Recall :  0.07878787878787878
F1 :  0.1287128712871287

In [43]:
#implementing GradientBoostingClassifier

gradient = GradientBoostingClassifier()
gradient.fit(without_out_train,out_train)
gradient_pred = gradient.predict(without_out_test)
gradient_score = accuracy_score(out_test,gradient_pred)
precission_gradient = precision_score(out_test,gradient_pred)
recall_gradient = recall_score(out_test,gradient_pred)
f1_gradient = f1_score(out_test,gradient_pred)
print("Accuracy : ",gradient_score)
print("Precission : ",precission_gradient)
print("Recall : ",recall_gradient)
print("F1 : ",f1_gradient)

Accuracy :  0.62
Precission :  0.20930232558139536
Recall :  0.05454545454545454
F1 :  0.08653846153846154

In [44]:
#implementing SVC

svc = SVC()
svc.fit(without_out_train,out_train)
svc_pred = svc.predict(without_out_test)
svc_score = accuracy_score(out_test,svc_pred)
precission_svc = precision_score(out_test,svc_pred)
recall_svc = recall_score(out_test,svc_pred)
f1_svc = f1_score(out_test,svc_pred)
print("Accuracy : ",svc_score)
print("Precission : ",precission_svc)
print("Recall : ",recall_svc)
print("F1 : ",f1_svc)

Accuracy :  0.67
Precission :  0.0
Recall :  0.0
F1 :  0.0

/home/moon/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))